FROM codebox/codebox.base:latest

# OpenJDK and JRE runtime
RUN apt-get install -y openjdk-7-jre-headless
RUN apt-get install -y openjdk-7-jdk

# Default init command
CMD su codebox /opt/codebox/init.sh

